# Generated by Django 4.2.2 on 2023-09-07 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
